name: AniList Data Sync

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install axios

    - name: Run AniList sync
      env:
        ANILIST_USERNAME: 'Swight'
        ANILIST_USER_ID: '6405416'
      run: |
        node anilist-sync.js

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add json/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update AniList data [skip ci]"
          git push
        fi
