name: Update AniList stats

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hourss
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Ensure the token has write permissions

jobs:
  update-anilist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install axios

    - name: Scrape AniList stats and update JSON
      run: node scripts/fetch_stats.js

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add stats.json
        git diff-index --quiet HEAD || git commit -m 'Update stats'
        git push